namespace IdentityMap.DataModel.Enums
{
    public enum ResourceType
    {
        Organization,
        Region,
        Office,
        Datacenter,
        PhysicalMachine,
        VirtualMachine,
        NetworkDevice,
        StorageDevice,
        CloudSubscription,
        CloudProvider,
        CloudRegion,
        OperatingSystem,
        BusinessApp,
        ServiceEndpoint,
        Queue,
        Database,
        Container,
        Cluster,
        Folder,
        File,
        DataStore,
        Account,
        ServiceAccount,
        Group,
        Role
    }
}
